#!/bin/bash

# generate /must-gather/version file
# shellcheck disable=SC1091
. version
echo "openshift-fusion-access/must-gather" > /must-gather/version # imageName - Source repo identifier
version >> /must-gather/version # imageVersion  - Build version
imageId >> /must-gather/version # imageID  -  repository@digest          

# Run the Collection of Resources using inspect
oc adm inspect --dest-dir must-gather --rotated-pod-logs --all-namespaces "ns/ibm-fusion-access"

exit 0
